# Generated by Django 2.1 on 2018-08-08 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippet',
            old_name='name',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='snippet',
            old_name='body',
            new_name='description',
        ),
        migrations.AddField(
            model_name='snippet',
            name='book_title',
            field=models.CharField(default='none', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='snippet',
            name='genre',
            field=models.CharField(default='none', max_length=50),
            preserve_default=False,
        ),
    ]
