# Generated by Django 2.1 on 2018-08-09 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20180808_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
