# Generated by Django 2.1 on 2018-08-09 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_snippet_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snippet',
            name='description',
        ),
    ]
